name: Gradle Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Report results to CodeCov
        uses: codecov/codecov-action@v2
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true 
      - name: Report results to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: java
          coverage-file: build/reports/jacoco/test/jacocoTestReport.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
